/**
 * Unified Azure Role Assignment implementation using VersionedAzapiResource framework
 *
 * This class provides a version-aware implementation for managing Azure Role Assignments
 * using the AZAPI provider. Role assignments grant specific permissions (roles) to security
 * principals (users, groups, service principals, managed identities) at a particular scope.
 *
 * Supported API Versions:
 * - 2022-04-01 (Active, Latest)
 *
 * Features:
 * - Automatic latest version resolution when no version is specified
 * - Explicit version pinning for stability requirements
 * - Schema-driven validation and transformation
 * - Support for all principal types (User, Group, ServicePrincipal, ForeignGroup, Device)
 * - Conditional role assignments using ABAC (Attribute-Based Access Control)
 * - Delegated managed identity support for group assignments
 * - Assignment at subscription, resource group, or resource scope
 * - JSII compliance for multi-language support
 */

import { createHash } from "crypto";
import * as cdktf from "cdktf";
import { Construct } from "constructs";
import {
  ALL_ROLE_ASSIGNMENT_VERSIONS,
  ROLE_ASSIGNMENT_TYPE,
} from "./role-assignment-schemas";
import {
  AzapiResource,
  AzapiResourceProps,
} from "../../core-azure/lib/azapi/azapi-resource";
import { ApiSchema } from "../../core-azure/lib/version-manager/interfaces/version-interfaces";

/**
 * Properties for the unified Azure Role Assignment
 *
 * Extends AzapiResourceProps with Role Assignment specific properties.
 *
 * **Note on the `name` property:** While this interface inherits the `name` property
 * from AzapiResourceProps, it is not used for role assignments. Azure role assignments
 * require GUID format names, which are automatically generated by the construct.
 * Any user-provided name value will be ignored in favor of Azure's deterministic
 * GUID generation based on the deployment context.
 */
export interface RoleAssignmentProps extends AzapiResourceProps {
  /**
   * The role definition ID to assign
   * This can be a built-in or custom role definition
   * Required property
   *
   * @example "/subscriptions/00000000-0000-0000-0000-000000000000/providers/Microsoft.Authorization/roleDefinitions/acdd72a7-3385-48ef-bd42-f606fba81ae7" (Reader)
   * @example "/providers/Microsoft.Authorization/roleDefinitions/b24988ac-6180-42a0-ab88-20f7382dd24c" (Contributor)
   */
  readonly roleDefinitionId: string;

  /**
   * The principal ID (object ID) to which the role is assigned
   * This can be a user, group, service principal, or managed identity
   * Required property
   *
   * @example "00000000-0000-0000-0000-000000000000"
   */
  readonly principalId: string;

  /**
   * The scope at which the role assignment is applied
   * Can be a subscription, resource group, or resource
   * Required property
   *
   * @example "/subscriptions/00000000-0000-0000-0000-000000000000"
   * @example "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/rg-name"
   * @example "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/rg-name/providers/Microsoft.Storage/storageAccounts/storage-name"
   */
  readonly scope: string;

  /**
   * The type of principal
   * Specifies what kind of identity is being assigned the role
   *
   * @default undefined (Azure will auto-detect)
   * @example "User" - An Azure AD user
   * @example "Group" - An Azure AD group
   * @example "ServicePrincipal" - A service principal (application)
   * @example "ForeignGroup" - A group from external directory
   * @example "Device" - A device identity
   */
  readonly principalType?: string;

  /**
   * The role assignment description
   * Provides detailed information about why the assignment was made
   *
   * @example "Grants read access to monitoring team for resource diagnostics"
   */
  readonly description?: string;

  /**
   * The conditions on the role assignment
   * Limits the resources it applies to using ABAC expressions
   * Requires conditionVersion to be set when used
   *
   * @example "@Resource[Microsoft.Storage/storageAccounts/blobServices/containers:name] StringEquals 'logs'"
   */
  readonly condition?: string;

  /**
   * Version of the condition syntax
   * Required when condition is specified
   *
   * @default undefined
   * @example "2.0"
   */
  readonly conditionVersion?: string;

  /**
   * The delegated Azure Resource Id which contains a Managed Identity
   * Applicable only when the principalType is Group
   * Used for scenarios where a group assignment should use a specific managed identity
   *
   * @example "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/rg/providers/Microsoft.ManagedIdentity/userAssignedIdentities/identity"
   */
  readonly delegatedManagedIdentityResourceId?: string;

  /**
   * The lifecycle rules to ignore changes
   * @example ["description"]
   */
  readonly ignoreChanges?: string[];
}

/**
 * Properties interface for Azure Role Assignment
 * This is required for JSII compliance to support multi-language code generation
 */
export interface RoleAssignmentProperties {
  /**
   * The role definition ID
   */
  readonly roleDefinitionId: string;

  /**
   * The principal ID
   */
  readonly principalId: string;

  /**
   * The scope of the role assignment
   */
  readonly scope: string;

  /**
   * The type of principal
   */
  readonly principalType?: string;

  /**
   * The role assignment description
   */
  readonly description?: string;

  /**
   * The conditions on the role assignment
   */
  readonly condition?: string;

  /**
   * Version of the condition syntax
   */
  readonly conditionVersion?: string;

  /**
   * The delegated managed identity resource ID
   */
  readonly delegatedManagedIdentityResourceId?: string;
}

/**
 * The resource body interface for Azure Role Assignment API calls
 * This matches the Azure REST API schema for role assignments
 */
export interface RoleAssignmentBody {
  /**
   * The properties of the role assignment
   */
  readonly properties: RoleAssignmentProperties;
}

/**
 * Unified Azure Role Assignment implementation
 *
 * This class provides a single, version-aware implementation for managing Azure
 * Role Assignments. It automatically handles version resolution, schema validation,
 * and property transformation.
 *
 * **Important Notes:**
 * - Role assignments are scoped resources deployed at subscription, resource group,
 *   or resource level. They do not have a location property as they are not region-specific.
 * - The `name` property (inherited from AzapiResourceProps) is not used. Azure automatically
 *   generates a deterministic GUID for role assignment names based on the deployment context.
 *   This ensures idempotent deployments without duplicate role assignments.
 *
 * @example
 * Basic role assignment - Assign Reader role to a user at subscription scope
 *
 * const assignment = new RoleAssignment(this, "reader-assignment", {
 *   roleDefinitionId: "/providers/Microsoft.Authorization/roleDefinitions/acdd72a7-3385-48ef-bd42-f606fba81ae7",
 *   principalId: "00000000-0000-0000-0000-000000000000",
 *   scope: "/subscriptions/00000000-0000-0000-0000-000000000000",
 *   principalType: "User",
 * });
 *
 * @example
 * Resource group scoped assignment - Assign Contributor to a service principal
 *
 * const assignment = new RoleAssignment(this, "contributor-assignment", {
 *   roleDefinitionId: "/providers/Microsoft.Authorization/roleDefinitions/b24988ac-6180-42a0-ab88-20f7382dd24c",
 *   principalId: servicePrincipal.objectId,
 *   scope: resourceGroup.id,
 *   principalType: "ServicePrincipal",
 *   description: "Grants contributor access to the deployment service principal",
 * });
 *
 * @example
 * Conditional assignment with ABAC - Limit access to specific storage containers
 *
 * const assignment = new RoleAssignment(this, "conditional-assignment", {
 *   roleDefinitionId: storageRole.id,
 *   principalId: user.objectId,
 *   scope: storageAccount.id,
 *   principalType: "User",
 *   condition: "@Resource[Microsoft.Storage/storageAccounts/blobServices/containers:name] StringEquals 'logs'",
 *   conditionVersion: "2.0",
 *   description: "Grants access only to the logs container",
 * });
 *
 * @stability stable
 */
export class RoleAssignment extends AzapiResource {
  static {
    AzapiResource.registerSchemas(
      ROLE_ASSIGNMENT_TYPE,
      ALL_ROLE_ASSIGNMENT_VERSIONS,
    );
  }

  /**
   * The input properties for this Role Assignment instance
   */
  public readonly props: RoleAssignmentProps;

  // Output properties for easy access and referencing
  public readonly idOutput: cdktf.TerraformOutput;
  public readonly nameOutput: cdktf.TerraformOutput;

  // Public properties

  /**
   * Creates a new Azure Role Assignment using the VersionedAzapiResource framework
   *
   * The constructor automatically handles version resolution, schema registration,
   * validation, and resource creation.
   *
   * @param scope - The scope in which to define this construct
   * @param id - The unique identifier for this instance
   * @param props - Configuration properties for the Role Assignment
   */
  constructor(scope: Construct, id: string, props: RoleAssignmentProps) {
    // Azure Role Assignments do not support tags at the resource level.
    // We must strip tags from props before passing to the parent constructor
    // to prevent the AZAPI provider from including tags in the resource.
    // eslint-disable-next-line @typescript-eslint/no-unused-vars
    const { tags: _unusedTags, ...propsWithoutTags } = props;
    super(scope, id, propsWithoutTags as RoleAssignmentProps);

    this.props = props;

    // Extract properties from the AZAPI resource outputs using Terraform interpolation

    // Create Terraform outputs for easy access and referencing from other resources
    this.idOutput = new cdktf.TerraformOutput(this, "id", {
      value: this.id,
      description: "The ID of the Role Assignment",
    });

    this.nameOutput = new cdktf.TerraformOutput(this, "name", {
      value: `\${${this.terraformResource.fqn}.name}`,
      description: "The name of the Role Assignment",
    });

    // Override logical IDs to match original naming convention
    this.idOutput.overrideLogicalId("id");
    this.nameOutput.overrideLogicalId("name");

    // Apply ignore changes if specified
    this._applyIgnoreChanges();
  }

  // =============================================================================
  // REQUIRED ABSTRACT METHODS FROM AzapiResource
  // =============================================================================

  /**
   * Gets the default API version to use when no explicit version is specified
   * Returns the most recent stable version as the default
   */
  protected defaultVersion(): string {
    return "2022-04-01";
  }

  /**
   * Gets the Azure resource type for Role Assignments
   */
  protected resourceType(): string {
    return ROLE_ASSIGNMENT_TYPE;
  }

  /**
   * Gets the API schema for the resolved version
   * Uses the framework's schema resolution to get the appropriate schema
   */
  protected apiSchema(): ApiSchema {
    return this.resolveSchema();
  }

  /**
   * Creates the resource body for the Azure API call
   * Transforms the input properties into the JSON format expected by Azure REST API
   *
   * Note: Role assignments do not have a location property as they are
   * scoped resources (subscription, resource group, or resource level).
   * The scope property is NOT included in the body as it's read-only and
   * automatically derived from the parentId.
   */
  protected createResourceBody(props: any): any {
    const typedProps = props as RoleAssignmentProps;
    return {
      properties: {
        roleDefinitionId: typedProps.roleDefinitionId,
        principalId: typedProps.principalId,
        // Note: scope is NOT included here - it's read-only and derived from parentId
        principalType: typedProps.principalType,
        description: typedProps.description,
        condition: typedProps.condition,
        conditionVersion: typedProps.conditionVersion,
        delegatedManagedIdentityResourceId:
          typedProps.delegatedManagedIdentityResourceId,
      },
    };
  }

  /**
   * Overrides the name resolution to generate deterministic GUIDs for role assignments
   *
   * Role assignments require GUID format IDs. This implementation generates a deterministic
   * UUID based on the role assignment's key properties to ensure:
   * - Same GUID is generated on re-deployments with same parameters
   * - Idempotent deployments (no duplicate role assignments)
   * - Consistent behavior across deployment runs
   */
  protected resolveName(props: AzapiResourceProps): string {
    const typedProps = props as RoleAssignmentProps;

    // Create a deterministic hash from key role assignment properties
    const hashInput = [
      typedProps.scope,
      typedProps.roleDefinitionId,
      typedProps.principalId,
    ].join("|");

    const hash = createHash("sha256").update(hashInput).digest("hex");

    // Convert hash to UUID format (8-4-4-4-12)
    return [
      hash.substring(0, 8),
      hash.substring(8, 12),
      hash.substring(12, 16),
      hash.substring(16, 20),
      hash.substring(20, 32),
    ].join("-");
  }

  /**
   * Overrides parent ID resolution to use the scope from props
   * Role assignments are scoped resources where the scope IS the parent
   */
  protected resolveParentId(props: any): string {
    const typedProps = props as RoleAssignmentProps;
    return typedProps.scope;
  }

  // =============================================================================
  // PUBLIC METHODS FOR ROLE ASSIGNMENT OPERATIONS
  // =============================================================================

  /**
   * Get the full resource identifier for use in other Azure resources
   * Alias for the id property
   */
  public get resourceId(): string {
    return this.id;
  }

  /**
   * Get the role definition ID this assignment references
   */
  public get roleDefinitionId(): string {
    return this.props.roleDefinitionId;
  }

  /**
   * Get the principal ID that was granted this role
   */
  public get principalId(): string {
    return this.props.principalId;
  }

  /**
   * Get the scope of this role assignment
   */
  public get assignmentScope(): string {
    return this.props.scope;
  }

  /**
   * Get the principal type
   */
  public get principalType(): string | undefined {
    return this.props.principalType;
  }

  // =============================================================================
  // PRIVATE HELPER METHODS
  // =============================================================================

  /**
   * Applies ignore changes lifecycle rules if specified in props
   * Always includes body.properties.roleDefinitionId to handle Azure API format normalization
   */
  private _applyIgnoreChanges(): void {
    // Always ignore roleDefinitionId format changes due to Azure API normalization
    // Azure returns subscription-qualified format but accepts non-qualified format
    const ignoreChanges = [
      "body.properties.roleDefinitionId",
      ...(this.props.ignoreChanges || []),
    ];

    this.terraformResource.addOverride("lifecycle", {
      ignore_changes: ignoreChanges,
    });
  }
}
