// generated by cdktf get
export * as dataPlaneResource from "./data-plane-resource";
export * as resource from "./resource";
export * as resourceAction from "./resource-action";
export * as updateResource from "./update-resource";
export * as dataAzapiClientConfig from "./data-azapi-client-config";
export * as dataAzapiResource from "./data-azapi-resource";
export * as dataAzapiResourceAction from "./data-azapi-resource-action";
export * as dataAzapiResourceId from "./data-azapi-resource-id";
export * as dataAzapiResourceList from "./data-azapi-resource-list";
export * as provider from "./provider";
