// generated by cdktf get
Object.defineProperty(exports, 'dataPlaneResource', { get: function () { return require('./data-plane-resource'); } });
Object.defineProperty(exports, 'resource', { get: function () { return require('./resource'); } });
Object.defineProperty(exports, 'resourceAction', { get: function () { return require('./resource-action'); } });
Object.defineProperty(exports, 'updateResource', { get: function () { return require('./update-resource'); } });
Object.defineProperty(exports, 'dataAzapiClientConfig', { get: function () { return require('./data-azapi-client-config'); } });
Object.defineProperty(exports, 'dataAzapiResource', { get: function () { return require('./data-azapi-resource'); } });
Object.defineProperty(exports, 'dataAzapiResourceAction', { get: function () { return require('./data-azapi-resource-action'); } });
Object.defineProperty(exports, 'dataAzapiResourceId', { get: function () { return require('./data-azapi-resource-id'); } });
Object.defineProperty(exports, 'dataAzapiResourceList', { get: function () { return require('./data-azapi-resource-list'); } });
Object.defineProperty(exports, 'provider', { get: function () { return require('./provider'); } });

