name: Internal Release

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'src/**/*.ts'
      - 'package.json'
      - '!**/*.spec.ts'
      - '!src/**/test/**'
      - '!**/*.go'
      - '!**/*.md'

jobs:
  publish-package:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
          registry-url: https://msasg.pkgs.visualstudio.com/PIQ/_packaging/PIQ_PublicPackages/npm/registry/
          always-auth: true

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Publish to Azure DevOps
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.AZURE_DEVOPS_PAT }}
