name: PR Pipeline

on:
  pull_request:
    branches:
      - main # or your default branch

jobs:
  npm-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20' # or your preferred version

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

  tfsec:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install tfsec
        run: |
          curl -L "https://github.com/tfsec/tfsec/releases/download/v0.58.14/tfsec-linux-amd64" > tfsec
          chmod +x tfsec
          sudo mv tfsec /usr/local/bin/

      - name: Run tfsec
        run: tfsec cdktf.out
