name: PR Pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  npm-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.5.0'

      - name: Install dependencies
        run: npm ci

      - name: Install azurerm-mock
        run: npm install -g azurerm-mock
      
      - name: Start azurerm-mock
        run: azurerm-mock &

      - name: Run tests
        run: npm test
        env:
          ARM_ENDPOINT: http://127.0.0.1:3000
          ARM_SUBSCRIPTION_ID: 00000000-0000-0000-0000-000000000000
          ARM_TENANT_ID: 00000000-0000-0000-0000-000000000000
          ARM_CLIENT_ID: 00000000-0000-0000-0000-000000000000
          ARM_CLIENT_SECRET: 00000000-0000-0000-0000-000000000000

  tfsec:
    needs: npm-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install tfsec
        run: |
          curl -L "https://github.com/tfsec/tfsec/releases/download/v0.58.14/tfsec-linux-amd64" > tfsec
          chmod +x tfsec
          sudo mv tfsec /usr/local/bin/

      - name: Run tfsec
        run: tfsec cdktf.out
